double deltaX;
double deltaY;
double distance;
Console.WriteLine("введите координату Х первой точки");
double x1 = double.Parse(Console.ReadLine());
Console.WriteLine("введите координату Y первой точки");
double y1 = double.Parse(Console.ReadLine());
Console.WriteLine("введите координату Х второй точки");
double x2 = double.Parse(Console.ReadLine());
Console.WriteLine("введите координату Y второй точки");
double y2 = double.Parse(Console.ReadLine());
deltaX = Math.Sqrt((x1 - x2) * (x1 - x2));
deltaY = Math.Sqrt((y1 - y2) * (y1 - y2));
distance = Math.Sqrt(deltaX * deltaX + deltaY * deltaY);
Console.WriteLine(deltaX);
Console.WriteLine(deltaY);
Console.WriteLine("расстояние между точками X и Y равно: " + distance);